version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5438:5432

  app-test:
    build: ./
    command: sh -c "./wait-for-postgres.sh db && cd app && pytest -v -p no:warnings"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - PYTHONPATH=./
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
