version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432

  cache:
    image: redis:latest
    restart: always
    ports:
      - 6378:6379

  app-menu:
    build: ./
    command: sh -c "./wait-for-postgres.sh db && cd app && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    depends_on:
      - db
      - cache
    environment:
      - DB_PASSWORD=qwerty
